### ISSUE TITLE
how to fix it?

### ISSUE THREAD

**Issue by ianchopel** [Sakurai07/Checkra1n.py#2]
C:\Users\Chopel Flasher\Downloads\Compressed\Checkra1n.py-main\Checkra1n.py-main>python ipwndfu -p
Traceback (most recent call last):
  File "C:\Users\Chopel Flasher\Downloads\Compressed\Checkra1n.py-main\Checkra1n.py-main\ipwndfu", line 47, in <module>
    device = dfu.acquire_device()
  File "C:\Users\Chopel Flasher\Downloads\Compressed\Checkra1n.py-main\Checkra1n.py-main\dfu.py", line 19, in acquire_device
    usb.util.claim_interface(device, 0)
  File "C:\Users\Chopel Flasher\Downloads\Compressed\Checkra1n.py-main\Checkra1n.py-main\usb\util.py", line 205, in claim_interface
    device._ctx.managed_claim_interface(device, interface)
  File "C:\Users\Chopel Flasher\Downloads\Compressed\Checkra1n.py-main\Checkra1n.py-main\usb\core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\Chopel Flasher\Downloads\Compressed\Checkra1n.py-main\Checkra1n.py-main\usb\core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "C:\Users\Chopel Flasher\Downloads\Compressed\Checkra1n.py-main\Checkra1n.py-main\usb\backend\libusb0.py", line 521, in claim_interface
    _check(_lib.usb_claim_interface(dev_handle, intf))
  File "C:\Users\Chopel Flasher\Downloads\Compressed\Checkra1n.py-main\Checkra1n.py-main\usb\backend\libusb0.py", line 431, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [claim_interface] could not claim interface 0, invalid configuration 0\n'

**Comment by wynwxst** [comment]
try doing the part mentioned in #important

**Comment by Wkaiming** [comment]
@ianchopel 

solve it ？

**Comment by Wkaiming** [comment]
@Ehnryu 

I also encountered it, restarted the computer many times, still not working

**Comment by wynwxst** [comment]
It means that libusb0 was not installed properly

**Comment by wynwxst** [comment]
https://www.smallcab.net/download/programme/xm-07/how-to-install-libusb-driver.pdf
